# Generated by Django 4.0.4 on 2022-05-25 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likerecord',
            name='tweetSlug',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='likerecord',
            name='userSlug',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='likerecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
