# Generated by Django 4.0.4 on 2022-05-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='title',
        ),
    ]
