# Generated by Django 4.0.4 on 2022-05-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_remove_tweet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
