# Generated by Django 4.0.4 on 2022-05-26 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweetapp', '0005_tweet_retweetslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetweetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userSlug', models.CharField(blank=True, max_length=30)),
                ('tweetSlug', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tweet', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweet_record', to='tweetapp.tweet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweet_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
